### ISSUE TITLE
Chinese Fonts between Operating Systems

### ISSUE THREAD

**Issue by qu-tan-um** [tbcdebug/PKU_EECS_UGR_THSS#4]
Kaiti is used in the cover, however on my Mac, it cannot be imported the way in the up-to-date files. Maybe it will work on Windows? @SceneryInMirror

**Comment by SceneryInMirror** [comment]
On Windows, I can use Kaiti because I have installed the font ‘楷体’ in the system file path: 'C:\Windows\Fonts'. Then I include these three lines in 'CoverHead.tex' to enable the command ‘\kaiti’:

\usepackage{xeCJK}
\setCJKfamilyfont{kaiti}[楷体]
\newcommand{\kaiti}{\CJKfamily{kaiti}}

So I think to solve the problem, you may need to check out available fonts in your machine, and install the missing fonts you need. Besides, the names of fonts may differ between different systems, so the reason could also be the font name is different.

By the way, I think these websites may be helpful:
* https://www.zhihu.com/question/20210754 (Zhihu: Using Chinese fonts in LaTeX on Mac)
* https://blog.csdn.net/u011606714/article/details/79321377 (When missing fonts on Mac)
* http://tieba.baidu.com/p/3361718855 (Settings of ctex on Mac)
* https://blog.csdn.net/penghouwen/article/details/50491177 (Config Chinese fonts in LaTex on Mac)

**Comment by qu-tan-um** [comment]
My non-ctex version was tailored to the fonts of Mac OS. I was just wondering if there's a middle ground here. I tried \CJKfamily{...} Kaiti, kaiti, Kai, kai, but none of these works on Mac OS.
